INSTALL_DIR=./bin

all:
	cd rrdtool-1.4.7 && ./configure --disable-tcl && make && make install 
#	cd rrdtool-1.4.7 && mkdir $(INSTALL_DIR) && ./configure --prefix=$(INSTALL_DIR) && make && make install

install:
	echo
